version: 2

mkdocs:
    configuration: docs/mkdocs.yml
    fail_on_warning: true

formats:
    - htmlzip

python:
  version: 3.7
  install:
      - requirements: requirements.txt
      - requirements: docs/requirements.txt
